version: '3.9'

services:
  mongo:
    image: cr.ntz.la/bb/mongo:green_prod
    ports:
      - '27017:27017'
    #healthcheck:
    #  test: echo 'db.runCommand({serverStatus:1}).ok' | /usr/bin/mongo admin --quiet | grep 1
    #  interval: 10s
    #  timeout: 10s
    #  retries: 3
    #  start_period: 20s
  geth:
    image: cr.ntz.la/bb/ethereum/geth-node
    ports:
      - '8545:8545'
    command: ['--rpc.allow-unprotected-txs']
  redis:
    image: redis
    ports:
      - '6379:6379'
  wallet-server:
    image: node:14
    ports:
      - '5000:5000'
      - '5001:5001'
    user: '${UID}:${GID}'
    volumes:
      - ./:/code
    working_dir: /code
    #command: bash -c "./scripts/wait-for-mongo.js && npm run dev"
    command: 'npm run dev'
    depends_on:
      - 'redis'
      - 'geth'
      - 'mongo'
