export enum ItemTokenName {
  BETA_KEY = 'BETA-KEY',
  ALFA_FOUNTAIN_OK = 'ALFA-FOUNTAIN-OK',
  ALFA_FOUNTAIN_GOOD = 'ALFA-FOUNTAIN-GOOD',
  ALFA_FOUNTAIN_GREAT = 'ALFA-FOUNTAIN-GREAT',
  ALFA_FOUNTAIN_MAJESTIC = 'ALFA-FOUNTAIN-MAJESTIC',
  EXPRESS_DEPOT = 'EXPRESS_DEPOT',
}
